Test/m5 env lib
AkariGroup/akari_software pull request #231
Opened 2024-02-23 14:27 UTC by kazyam53

- ENV4もM5のUnitEnvで公式対応されたので、そちらに統合
- UnitEnvを改造して温度を測定できるようにしていたが、その機能が公式にも反映されていたので、改造版は破棄
- 環境センサなしでも動作するように変更。使わない場合は付けなくても使えるように。

2024-03-29 14:26 UTC, kazyam53 commented
@Wisteria720 
UnitENVの公式レポジトリが修正されて使えるようになったので、レビューお願いします！

2024-04-01 00:41 UTC, Wisteria720 requested changes
確認しました
1点修正お願いします

2024-04-01 00:41 UTC, Wisteria720 commented on setup/arduino/src/m5base_for_akari.ino
>    }
この”}”が不要だと思います
コンパイルエラーで書き込みできませんでした

2024-04-01 02:04 UTC, kazyam53 commented on setup/arduino/src/m5base_for_akari.ino
>    }
すいません、直しました。
確認したつもりが…申し訳ないです。

2024-04-01 02:06 UTC, kazyam53 commented
@Wisteria720 
コンパイルエラー修正、動確しましたので確認お願いします。
フォーマットも行ってしまいましたが、コード変わったのは指摘いただいたところだけです。

2024-04-01 05:25 UTC, Wisteria720 approved these changes
確認しました
ENV-Ⅳが手元にない為、動作確認はⅢと”未接続”のみです

2024-04-01 05:27 UTC, merged